version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  build:
    desc: Compile the PocketBase server binary
    cmds:
      - go build -o pb-server .

  serve:
    desc: Run PocketBase in dev mode with Go migrations
    cmds:
      - go run . serve --dev --migrationsDir ./migrations

  migrate:
    desc: Apply PocketBase migrations
    cmds:
      - go run . migrate --migrationsDir ./migrations

  test:
    desc: Execute Go unit tests
    cmds:
      - go test ./...

  tidy:
    desc: Format and tidy the Go module
    cmds:
      - go fmt ./...
      - go mod tidy

  reset:
    desc: Delete the PocketBase data directory (pb_data)
    cmds:
      - rm -rf pb_data
      - go run . superuser upsert admin@example.com changeme123

  frontend:install:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - npm install

  frontend:dev:
    desc: Start the Vite dev server with hot reload
    dir: frontend
    cmds:
      - npm run dev -- --host

  frontend:build:
    desc: Build the production React bundle
    dir: frontend
    cmds:
      - npm run build
