version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  build:
    desc: Compile the PocketBase server binary
    cmds:
      - go build -o pb-server .

  serve:
    desc: Run PocketBase in dev mode with Go migrations
    cmds:
      - go run . serve --dev --migrationsDir ./migrations

  test:
    desc: Execute Go unit tests
    cmds:
      - go test ./...

  tidy:
    desc: Format and tidy the Go module
    cmds:
      - go fmt ./...
      - go mod tidy
